backend:
  build: .
  dns:
    - 8.8.8.8
    - 1.1.1.1
    - 100.100.100.100
  ports:
    - "3000:3000"
  volumes:
    - .:/app
    - /app/node_modules
  env_file:
    - .env
  environment:
    - NODE_ENV=production
  depends_on:
    db:
      condition: service_healthy
  restart: unless-stopped
  networks:
    - app-network
